#!/bin/sh

URL=$1
TOKEN=$2

curl -H "Private-Token: ${TOKEN}" ${URL}/api/v4/users?per_page=1000 > /tmp/gitlab_users.json
jq -r '. | map(.username), map(.name), map(.email), map(.state), map(.last_activity_on) | @csv' < /tmp/gitlab_users.json | csvtool transpose -
